services:
  postgres:
    image: postgres:latest
    container_name: auth_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: authDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - auth_network

  app:
    build: .
    container_name: auth_app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: authDB
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_network

volumes:
  postgres_data: {}
networks:
  auth_network:
    driver: bridge